name: Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      releaseName:
        description: 'Name of the release'
        required: false
        default: ""

jobs:
  build:
    runs-on: Linux #linux internal

    steps:
      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: "/bin/rm /github/workspace -rf"

      - uses: actions/checkout@v2
        with:
          ref: main
          #token: ${{ secrets.GHA_PERSONNAL_ADMIN_TOKEN }} #If main is protected, you need to use an admin personnal token

      - name: Checkout GitHub Action Repo 
        uses: actions/checkout@v2
        with:
          repository: dktunited/member-actions
          ref: v1
          token: ${{ secrets.DKTUNITED_TOKEN }}
          path: .github/member-actions

      - name: Setup variables
        uses: ./.github/member-actions/github-action-member-setup-env

      - name: Get version
        run: |
          echo 'Change sources version according to maven= maven +1'
          version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$version">> $GITHUB_ENV

      - name: Login to Container Registry Europe
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.MEMBER_DOCKER_REGISTRY_EUROPE }}
          username: ${{ secrets.MEMBER_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.MEMBER_DOCKER_REGISTRY_PASSWORD }}

      - name: Docker Push
        run: |
          docker image pull ${{ secrets.MEMBER_DOCKER_REGISTRY_EUROPE }}/member-worldwide-utes/member-worldwide-eu/${{ env.ghrepo }}:SNAPSHOT-${{ env.VERSION }}
          docker image tag ${{ secrets.MEMBER_DOCKER_REGISTRY_EUROPE }}/member-worldwide-utes/member-worldwide-eu/${{ env.ghrepo }}:SNAPSHOT-${{ env.VERSION }} ${{ secrets.MEMBER_DOCKER_REGISTRY_EUROPE }}/member-worldwide-utes/member-worldwide-eu/${{ env.ghrepo }}:${{env.VERSION}}
          docker push ${{ secrets.MEMBER_DOCKER_REGISTRY_EUROPE }}/member-worldwide-utes/member-worldwide-eu/${{ env.ghrepo }}:${{ env.VERSION }}

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: RELEASE-${{env.VERSION}}
          release_name: ${{ github.event.inputs.releaseName }} ${{env.VERSION}}
          draft: false
          prerelease: false

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          release_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version on main
        run: |
          echo 'Change sources version according to maven= maven +1'
          mvn -q build-helper:parse-version versions:set \
            -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0 \
            versions:commit
          version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$version">> $GITHUB_ENV

      - name: Push bump on main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI: Change version to ${{ env.VERSION }}"
          push_options: '--force'
          branch: main
